[project]
name = "backend"
version = "0.1.0"
description = "Simple SQL Dev Endpoints"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.120.3",
    "numpy>=1.24.4",
    "pandas>=2.0.3",
]
